name: "Continuous Integration"

on: [push, pull_request, workflow_dispatch]

jobs:
  unittest:
    name: "Run the unit-tests"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.2"
          - "7.3"
          - "8.0"
          - "8.1"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          ini-values: error_reporting=-1, display_errors=On, zend.assertions=1
          tools: "composer:v2"
          php-version: "${{ matrix.php-version }}"

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress --prefer-dist"

      - name: "Run the unit-tests"
        run: "composer phpunit"

  fulltest:
    name: "Run all tests (7.4)"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          ini-values: error_reporting=-1, display_errors=On, zend.assertions=1
          tools: composer:v2, composer-normalize
          php-version: "7.4"

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress --prefer-dist"

      - name: "Run all tests"
        run: "composer test"

      - name: "Normalize composer.json"
        run: "composer-normalize --dry-run --no-check-lock --no-update-lock"
