name: "SonarCloud Analysis"

on:
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: "Install PHP"
      uses: "shivammathur/setup-php@v2"
      with:
        coverage: "pcov"
        tools: "composer:v2"
        php-version: "7.4"

    - name: "Install dependencies"
      run: "composer install --no-interaction --no-progress --prefer-dist"

    - name: "Calculate code coverage"
      run: "composer phpunit -- --coverage-clover=reports/coverage.clover --log-junit=reports/test.xml"

    - name: "Fix code coverage paths"
      working-directory: ./reports
      run: |
        sed -i 's/\/home\/runner\/work\/${{ github.event.repository.name }}\/${{ github.event.repository.name }}\///g' coverage.clover
        sed -i 's/\/home\/runner\/work\/${{ github.event.repository.name }}\/${{ github.event.repository.name }}\///g' test.xml

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
